from distutils.core import setup

import os

# find . -type f ! -name '*.py' ! -path './.git/*' ! -path './__pycache__/*'

files = """requirements.txt
Pipfile.lock
stockfish_versions/stockfish-ubuntu-20.04-x86-64-avx2
stockfish_versions/stockfish-windows-2022-x86-64-avx2.exe
stockfish_versions/stockfish-ubuntu-20.04-x86-64
stockfish_versions/stockfish_15.1_x64_bmi2
stockfish_versions/stockfish-ubuntu-20.04-x86-64-modern
stockfish_versions/stockfish-windows-2022-x86-64-modern.exe
stockfish_versions/readme.txt
assets/textures/chars/d.png
assets/textures/chars/4.png
assets/textures/chars/f.png
assets/textures/chars/g.png
assets/textures/chars/8.png
assets/textures/chars/b.png
assets/textures/chars/2.png
assets/textures/chars/e.png
assets/textures/chars/6.png
assets/textures/chars/3.png
assets/textures/chars/1.png
assets/textures/chars/h.png
assets/textures/chars/c.png
assets/textures/chars/a.png
assets/textures/chars/5.png
assets/textures/chars/7.png
assets/textures/board/regular/light.png
assets/textures/board/regular/dark.png
assets/textures/board/wooden/light.png
assets/textures/board/wooden/dark.png
assets/textures/board/wooden/orig_light.png
assets/textures/buttons/icons/settings.png
assets/textures/buttons/icons/empty.png~
assets/textures/buttons/icons/knight.png
assets/textures/buttons/icons/bishop.png
assets/textures/buttons/icons/queen.png
assets/textures/buttons/icons/close.png
assets/textures/buttons/icons/refresh.png
assets/textures/buttons/icons/pause.png
assets/textures/buttons/icons/restart.png
assets/textures/buttons/icons/volume_down.png
assets/textures/buttons/icons/hover/settings.png
assets/textures/buttons/icons/hover/knight.png
assets/textures/buttons/icons/hover/bishop.png
assets/textures/buttons/icons/hover/queen.png
assets/textures/buttons/icons/hover/close.png
assets/textures/buttons/icons/hover/refresh.png
assets/textures/buttons/icons/hover/pause.png
assets/textures/buttons/icons/hover/restart.png
assets/textures/buttons/icons/hover/volume_down.png
assets/textures/buttons/icons/hover/rook.png
assets/textures/buttons/icons/hover/remove.png
assets/textures/buttons/icons/hover/volume_up.png
assets/textures/buttons/icons/hover/help.png
assets/textures/buttons/icons/hover/add.png
assets/textures/buttons/icons/hover/play.png
assets/textures/buttons/icons/hover/play_random.png
assets/textures/buttons/icons/hover/play_white.png
assets/textures/buttons/icons/hover/play_black.png
assets/textures/buttons/icons/rook.png
assets/textures/buttons/icons/remove.png
assets/textures/buttons/icons/volume_up.png
assets/textures/buttons/icons/help.png
assets/textures/buttons/icons/on_pressed/settings.png
assets/textures/buttons/icons/on_pressed/knight.png
assets/textures/buttons/icons/on_pressed/bishop.png
assets/textures/buttons/icons/on_pressed/queen.png
assets/textures/buttons/icons/on_pressed/close.png
assets/textures/buttons/icons/on_pressed/refresh.png
assets/textures/buttons/icons/on_pressed/pause.png
assets/textures/buttons/icons/on_pressed/restart.png
assets/textures/buttons/icons/on_pressed/volume_down.png
assets/textures/buttons/icons/on_pressed/rook.png
assets/textures/buttons/icons/on_pressed/remove.png
assets/textures/buttons/icons/on_pressed/volume_up.png
assets/textures/buttons/icons/on_pressed/help.png
assets/textures/buttons/icons/on_pressed/add.png
assets/textures/buttons/icons/on_pressed/play.png
assets/textures/buttons/icons/on_pressed/play_random.png
assets/textures/buttons/icons/on_pressed/play_white.png
assets/textures/buttons/icons/on_pressed/play_black.png
assets/textures/buttons/icons/queen.png~
assets/textures/buttons/icons/add.png
assets/textures/buttons/icons/play.png
assets/textures/buttons/icons/play_random.png
assets/textures/buttons/icons/play_white.png
assets/textures/buttons/icons/play_black.png
assets/textures/buttons/icons/empty.png
assets/textures/buttons/play/ai.png
assets/textures/buttons/play/empty.png~
assets/textures/buttons/play/lvl1.png
assets/textures/buttons/play/hover/ai.png
assets/textures/buttons/play/hover/lvl1.png
assets/textures/buttons/play/hover/lvl3.png
assets/textures/buttons/play/hover/lvl2.png
assets/textures/buttons/play/hover/lvl4.png
assets/textures/buttons/play/hover/analyse.png
assets/textures/buttons/play/hover/lvl5.png
assets/textures/buttons/play/hover/player.png
assets/textures/buttons/play/hover/empty.png
assets/textures/buttons/play/lvl3.png
assets/textures/buttons/play/lvl2.png
assets/textures/buttons/play/lvl4.png
assets/textures/buttons/play/analyse.png
assets/textures/buttons/play/on_pressed/ai.png
assets/textures/buttons/play/on_pressed/lvl1.png
assets/textures/buttons/play/on_pressed/lvl3.png
assets/textures/buttons/play/on_pressed/lvl2.png
assets/textures/buttons/play/on_pressed/lvl4.png
assets/textures/buttons/play/on_pressed/analyse.png
assets/textures/buttons/play/on_pressed/lvl5.png
assets/textures/buttons/play/on_pressed/player.png
assets/textures/buttons/play/on_pressed/empty.png
assets/textures/buttons/play/lvl5.png
assets/textures/buttons/play/player.png
assets/textures/buttons/play/empty.png
assets/textures/pieces/regular/black/pawn.png
assets/textures/pieces/regular/black/knight.png
assets/textures/pieces/regular/black/bishop.png
assets/textures/pieces/regular/black/queen.png
assets/textures/pieces/regular/black/king.png
assets/textures/pieces/regular/black/rook.png
assets/textures/pieces/regular/white/pawn.png
assets/textures/pieces/regular/white/knight.png
assets/textures/pieces/regular/white/bishop.png
assets/textures/pieces/regular/white/queen.png
assets/textures/pieces/regular/white/king.png
assets/textures/pieces/regular/white/rook.png
assets/textures/pieces/wooden/black/pawn.png
assets/textures/pieces/wooden/black/knight.png
assets/textures/pieces/wooden/black/bishop.png
assets/textures/pieces/wooden/black/queen.png
assets/textures/pieces/wooden/black/king.png
assets/textures/pieces/wooden/black/rook.png
assets/textures/pieces/wooden/white/pawn.png
assets/textures/pieces/wooden/white/knight.png
assets/textures/pieces/wooden/white/bishop.png
assets/textures/pieces/wooden/white/queen.png
assets/textures/pieces/wooden/white/king.png
assets/textures/pieces/wooden/white/rook.png
assets/textures/pieces/circle.png
assets/textures/pieces/shadow.png
assets/textures/icon.png
assets/sources.txt
assets/fonts/main.ttf
Pipfile
ai/common.json
ai/lvl4.json
ai/lvl5.json
ai/lvl2.json
ai/lvl3.json
ai/lvl1.json
README.md
.gitignore""".split(
    "\n"
)


setup(
    name="PyChess",
    version="1.0",
    description="A GUI chess written in Python.",
    author="Nikli Erik",
    author_email="erik200203@gmail.com",
    url="https://github.com/niklierik/pychess",
    packages=["actors", "scenes", "ai", "assets", "game", "stockfish_versions"],
    py_modules=["main", "__main__"],
    install_requires=["pygame", "chess", "pylint"],
    data_files=[("", files)],
)
